server:
  port: 8080
spring:
  datasource:
    platform: postgres
    url: ${DB_URL}
    username: ${DB_LOGIN}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      max-lifetime: 600000
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql: trace
